// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mujoL4gD3qd1ezKDLZ31rZ
// Component: JmW7BQJp6k
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import { useMode } from "./PlasmicGlobalVariant__Mode" // plasmic-import: zulsK3o-3W/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_jeffdo_es.module.css" // plasmic-import: mujoL4gD3qd1ezKDLZ31rZ/projectcss
import * as sty from "./PlasmicTooltip.module.css" // plasmic-import: JmW7BQJp6k/css

export const PlasmicTooltip__VariantProps = new Array("bg")

export const PlasmicTooltip__ArgProps = new Array("color", "content")

function PlasmicTooltip__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props
  const globalVariants = ensureGlobalVariants({
    mode: useMode(),
  })

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_mixins,
        projectcss.plasmic_tokens,
        sty.root,
        {
          [projectcss.global_mode_dark]: hasVariant(
            globalVariants,
            "mode",
            "dark"
          ),

          [sty.rootbg_blue]: hasVariant(variants, "bg", "blue"),
          [sty.rootbg_grey]: hasVariant(variants, "bg", "grey"),
          [sty.rootbg_mint]: hasVariant(variants, "bg", "mint"),
          [sty.rootbg_orange]: hasVariant(variants, "bg", "orange"),
          [sty.rootbg_purple]: hasVariant(variants, "bg", "purple"),
          [sty.rootbg_red]: hasVariant(variants, "bg", "red"),
          [sty.rootbg_yellow]: hasVariant(variants, "bg", "yellow"),
        }
      )}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <div
            className={classNames(
              projectcss.all,
              projectcss.__wab_text,
              sty.text___4Lrap
            )}
          >
            {"about jeff"}
          </div>
        ),

        value: args.content,
        className: classNames(sty.slotTargetContent, {
          [sty.slotTargetContentbg_blue]: hasVariant(variants, "bg", "blue"),
          [sty.slotTargetContentbg_grey]: hasVariant(variants, "bg", "grey"),
          [sty.slotTargetContentbg_mint]: hasVariant(variants, "bg", "mint"),
          [sty.slotTargetContentbg_orange]: hasVariant(
            variants,
            "bg",
            "orange"
          ),

          [sty.slotTargetContentbg_purple]: hasVariant(
            variants,
            "bg",
            "purple"
          ),

          [sty.slotTargetContentbg_red]: hasVariant(variants, "bg", "red"),
          [sty.slotTargetContentbg_yellow]: hasVariant(
            variants,
            "bg",
            "yellow"
          ),
        }),
      })}
    </div>
  )
}

const PlasmicDescendants = {
  root: ["root"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicTooltip__ArgProps,
      internalVariantPropNames: PlasmicTooltip__VariantProps,
    })

    return PlasmicTooltip__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicTooltip"
  } else {
    func.displayName = `PlasmicTooltip.${nodeName}`
  }
  return func
}

export const PlasmicTooltip = Object.assign(
  // Top-level PlasmicTooltip renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicTooltip
    internalVariantProps: PlasmicTooltip__VariantProps,
    internalArgProps: PlasmicTooltip__ArgProps,
  }
)

export default PlasmicTooltip
/* prettier-ignore-end */
