// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mujoL4gD3qd1ezKDLZ31rZ
// Component: SiSovdu-fA
import * as React from "react"
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
} from "@plasmicapp/react-web"
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_jeffdo_es.module.css" // plasmic-import: mujoL4gD3qd1ezKDLZ31rZ/projectcss
import * as sty from "./PlasmicCaseStudy.module.css" // plasmic-import: SiSovdu-fA/css

export const PlasmicCaseStudy__VariantProps = new Array("project")

export const PlasmicCaseStudy__ArgProps = new Array()

function PlasmicCaseStudy__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props
  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.root
      )}
    />
  )
}

const PlasmicDescendants = {
  root: ["root"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCaseStudy__ArgProps,
      internalVariantPropNames: PlasmicCaseStudy__VariantProps,
    })

    return PlasmicCaseStudy__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "root") {
    func.displayName = "PlasmicCaseStudy"
  } else {
    func.displayName = `PlasmicCaseStudy.${nodeName}`
  }
  return func
}

export const PlasmicCaseStudy = Object.assign(
  // Top-level PlasmicCaseStudy renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicCaseStudy
    internalVariantProps: PlasmicCaseStudy__VariantProps,
    internalArgProps: PlasmicCaseStudy__ArgProps,
  }
)

export default PlasmicCaseStudy
/* prettier-ignore-end */
