// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: mujoL4gD3qd1ezKDLZ31rZ
// Component: IQmvc6tT46
import * as React from "react"
import * as p from "@plasmicapp/react-web"
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants,
} from "@plasmicapp/react-web"
import { useMode } from "./PlasmicGlobalVariant__Mode" // plasmic-import: zulsK3o-3W/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css"
import * as projectcss from "./plasmic_jeffdo_es.module.css" // plasmic-import: mujoL4gD3qd1ezKDLZ31rZ/projectcss
import * as sty from "./PlasmicWorkCard.module.css" // plasmic-import: IQmvc6tT46/css
import orgDesignMeo1PxVz7 from "./images/orgDesign.png" // plasmic-import: meo1PxVZ7/picture

export const PlasmicWorkCard__VariantProps = new Array()

export const PlasmicWorkCard__ArgProps = new Array("image", "title")

function PlasmicWorkCard__RenderFunc(props) {
  const { variants, args, overrides, forNode } = props
  const globalVariants = ensureGlobalVariants({
    mode: useMode(),
  })

  return (
    <div
      data-plasmic-name={"card"}
      data-plasmic-override={overrides.card}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        projectcss.all,
        projectcss.root_reset,
        projectcss.plasmic_default_styles,
        projectcss.plasmic_tokens,
        sty.card,
        "work-card",
        {
          [projectcss.global_mode_dark]: hasVariant(
            globalVariants,
            "mode",
            "dark"
          ),
        }
      )}
      tabIndex={0}
    >
      {p.renderPlasmicSlot({
        defaultContents: (
          <p.PlasmicImg
            alt={""}
            className={classNames(sty.img__lEXel)}
            displayHeight={"100%"}
            displayMaxHeight={"none"}
            displayMaxWidth={"100%"}
            displayMinHeight={"0"}
            displayMinWidth={"0"}
            displayWidth={"100%"}
            loading={"lazy"}
            src={{
              src: orgDesignMeo1PxVz7,
              fullWidth: 2880,
              fullHeight: 2048,
              aspectRatio: undefined,
            }}
          />
        ),

        value: args.image,
      })}

      <div className={classNames(projectcss.all, sty.freeBox__nzVMu)}>
        <div className={classNames(projectcss.all, sty.freeBox__haSw)}>
          {p.renderPlasmicSlot({
            defaultContents: "an org design tool",
            value: args.title,
            className: classNames(sty.slotTargetTitle),
          })}
        </div>
      </div>
    </div>
  )
}

const PlasmicDescendants = {
  card: ["card"],
}

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicWorkCard__ArgProps,
      internalVariantPropNames: PlasmicWorkCard__VariantProps,
    })

    return PlasmicWorkCard__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName,
    })
  }
  if (nodeName === "card") {
    func.displayName = "PlasmicWorkCard"
  } else {
    func.displayName = `PlasmicWorkCard.${nodeName}`
  }
  return func
}

export const PlasmicWorkCard = Object.assign(
  // Top-level PlasmicWorkCard renders the root element
  makeNodeComponent("card"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicWorkCard
    internalVariantProps: PlasmicWorkCard__VariantProps,
    internalArgProps: PlasmicWorkCard__ArgProps,
  }
)

export default PlasmicWorkCard
/* prettier-ignore-end */
