// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react"
import { PlasmicIconButton } from "./plasmic/jeffdo_es/PlasmicIconButton"

function IconButton_(props, ref) {
  return <PlasmicIconButton root={{ ref }} {...props} render="bleh"/>
}

const IconButton = React.forwardRef(IconButton_)

export default IconButton
